# The package collection to use
collection = "nightly-241110"

[install]

# Whether to install packages together with their
# sources or not. This is mainly useful for programmers
# who have set their editor up with some *go to definition*
# functionality (for instance by using idris2-lsp with neovim).
with-src   = true

# Whether to install API docs together with installed
# libraries.
with-docs = true

# Whether to use katla to generate HTML links to
# semantically highlighted API sources
use-katla = true

# Whether to prompt the user before building or installing
# packages or applications with custom build hooks in their
# `.ipkg` file.
safety-prompt = true

# Whether to prompt the user before running the garbage collector
# via command `gc`.
gc-prompt = true

# Whether to issue a warning in presence of a local `depends` directory
# which might interfere with the libraries managed by pack
warn-depends = true

# List of packages and apps with custom build hooks we trust to
# be safe. This gives more fine grained control over package safety
# than `safety-prompt`.
whitelist = [ "pack", "idris2-lsp" ]

# Must-have libraries. These will be installed automatically
# when using a new package collection.
# libs       = [ "toml", "elab-util" ]

# Must-have applications. These will be installed automatically
# when using a new package collection.
# apps       = [ "idris2-lsp" ]

[pack]

# Override this to use a custom Git repo for pack
# url = "https://github.com/stefan-hoeck/idris2-pack"

# Override this to use a custom commit and branch for pack
# commit = "latest:main"

[idris2]

# Whether to build Idris2 with its bootstrap compiler.
# Bootstrapping takes longer than building with an existing
# Idris2 installation, but it will work even if the existing
# Idris2 compiler is outdated.
bootstrap  = false

# Name or path to the scheme executable to use.
scheme      = "scheme"

# Default code generator to us
# codegen     = "chez"

# Set this to `true` in order to run REPL sessions from within
# `rlwrap`. This will give you additional features such as a
# command history.
# Alternatively, you can pass additional command-line arguments
# to `rlwrap` by setting this to a string or an array of strings,
# e.g. to "-pGreen -aN" or ["-pGreen", "--no-children"].
repl.rlwrap = true

# Packages to load automatically when starting a REPL session
# without an `.ipkg` file in scope. This defaults to "none".
# Note: Uncomment only one of the following examples:
# repl.autoload   = "installed"
# repl.autoload   = "autolibs"
# repl.autoload   = [ "sop", "toml" ]

# Override this to use a custom Git repo for the Idris compiler
# url = "https://github.com/idris-lang/Idris2"

# Override this to use a custom commit and branch for the Idris compiler
# commit = "latest:main"

# Below are some examples for custom packages

# A local package to be available with all
# package collections. The path to the package's root
# directory can be absolute or relative. In the latter
# case, it will be considered to be relative to the
# parent directory of the `pack.toml` file where it is
# defined.
#
# The path to `.ipkg` files must always relative to the
# given `path`.
# [custom.all.chem]
# type = "local"
# path = "/data/idris/chem"
# ipkg = "chem.ipkg"

[custom.all.async-epoll]
type = "local"
path = "/home/brian/Apps/idris2-async/async-epoll"
ipkg = "async-epoll.ipkg"

# A package as a Git repository to be available with all
# package collections.
# [custom.all.foo]
# type = "git"
# url  = "https://github.com/bar/foo"
# ipkg = "foo.ipkg"

[custom.all.idrisGL]
type = "git"
url  = "https://github.com/BrianNormant/Idris2GL"
ipkg = "idrisGL.ipkg"
commit = "2fc40b8b0fb3878db034f30c0397c5e371ab8038"


[custom.all.containers]
type = "git"
url = "https://github.com/BrianNormant/idris2-containers"
ipkg = "containers.ipkg"
commit = "8e8fc1ad614c00d0eaa8784a57533c34b59a2338"

# Override library `toml` from package collection `nightly-220503`
# by using a custom commit hash.
# [custom.nightly-220503.toml]
# type   = "git"
# url    = "https://github.com/cuddlefishie/toml-idr"
# commit = "eb7a146f565276f82ebf30cb6d5502e9f65dcc3c"
# ipkg   = "toml.ipkg"

# Uncomment and adjust the following entries to specify the
# default log level associated with each pack command.
# [log]

# exec = "debug"
# run  = "info"
# test = "warning"
