if [[ -n $TMUX ]]; then
	zstyle ':fzf-tab:*' fzf-command ftb-tmux-popup
fi

if [[ -n $NEOVIDE ]]; then
	zstyle ':fzf-tab:*' fzf-command fzf
	unset TMUX # Not sure if something needs tmux to be set?
fi

function playerctl() {
	eval `systemctl --user show-environment | grep CURRENT_PLAYER`
	env playerctl -p "$CURRENT_PLAYER" $*
}

export NH_HOME_FLAKE="/home/brian/.config/home-manager"
export PAGER="ov"
export SYSTEMD_PAGER="ov"
export SYSTEMD_SECURE="true"
export MANPAGER='vim +Man!'
export EDITOR="vim"
export VISUAL="vim"
export TERMINAL="kitty"

eval "$(zoxide init zsh)"

# Edit command in vim with <C-x><C-e>
autoload edit-command-line
zle -N edit-command-line
bindkey -M vicmd "^X^E" edit-command-line
bindkey -M viins "^X^E" edit-command-line

#To be hooked with nix shells
eval "$CMD"
