export NH_HOME_FLAKE="/home/brian/.config/home-manager"
export PAGER="ov"
export SYSTEMD_PAGER="ov"
export SYSTEMD_SECURE="true"
export MANPAGER='vim +Man!'
export EDITOR="vim"
export VISUAL="vim"
export TERMINAL="kitty"
export PATH="$PATH:$HOME/.local/bin"

alias nvim=nvim-cat

eval "$(zoxide init zsh)"

# Edit command in vim with <C-x><C-e>
autoload edit-command-line
zle -N edit-command-line
bindkey -M vicmd "^X" edit-command-line
bindkey -M viins "^X" edit-command-line
zvm_after_init() {
	bindkey "^X" history-incremental-pattern-search-backward
}

function playerctl() {
	eval `systemctl --user show-environment | grep CURRENT_PLAYER`
	env playerctl -p "$CURRENT_PLAYER" $*
}

# detach from tmux instead of killing the session.
# This could use some work to only detach if the session has 1 pane.
# As the simple way to kill a pane is "Ctrl-d".
stty eof '' # let zsh handle ctrl-d
function smart_ctrl_d() {
	if [[ -n $IN_NIX_SHELL ]]; then
		exit
	elif [[ -n $NVIM ]]; then
		exit
	elif [[ -n $TMUX ]]; then
		if [[ $( tmux display-message -p '#S' ) == 'PopUp' ]]; then
			exit
		else
			tmux detach
		fi
	else
		exit
	fi
}
zle -N smart_ctrl_d
bindkey '^D' smart_ctrl_d

if [[ $- == *i* ]]; then
	if [[ -n $NEOVIDE ]]; then
		zstyle ':fzf-tab:*' fzf-command fzf
		unset TMUX # Not sure if something needs tmux to be set?
	elif [[ -n $TMUX ]]; then
		zstyle ':fzf-tab:*' fzf-command ftb-tmux-popup
	elif [[ -o login ]]; then
		# do not start tmux on the login shell
	else
		max_empty_sessions=5
		tmux_sessions=()
		for i in {1..$max_empty_sessions}; do
			tmux_sessions+=('Main-'$i)
		done

		local found_session=0
		for session in $tmux_sessions; do
			if (tmux has-session -t $session ); then
				clients=$(tmux list-clients -t $session 2> /dev/null | wc -l)
				if [[ $clients -eq 0 ]]; then
					# we have a empty session, attach then exit
					found_session=1
					tmux attach -t $session
					break
				else
					# Session is aldready attached to, try the next one
					continue
				fi
			else
				# Session does not exist, create and attach
				tmux attach -t $session || tmux new -s $session
				found_session=1
				break
			fi
		done
		if [[ $found_session -eq 0 ]]; then
			# No empty session found, attach to any
			tmux attach -t Main-1 || tmux new -s Main-1
		fi
	fi
fi

#To be hooked with nix shells
eval "$CMD"
